### ISSUE TITLE
If color plate is not closed color won't select

### ISSUE THREAD

**Issue by aamirshahzad** [mjolnic/bootstrap-colorpicker#102]
I was facing an issue in color picker I have done fix;
Step to reproduce issue;
1) Click to open color picker
2) Drag to change any color 
3) Without clicking on body tag to close
4) Click on an button to save the color.(In my case there is a button that takes the changed value from 
`<span class="add-on">
   <i style="background-color: rgb(43, 43, 43);"></i>
</span>`
and on close it sets it into;
`<span class="color-value ">#262323</span>`
When color plate is closed.)
5) Color plate will not close need to add html element along with body to overcome compatibility issue
Issue: If color plate is not closed i.e. not clicked on the body it will not set the color.
body click is not triggered on button and anchors with return statement. Its pretty known issue for this kind of stuff. You can test it as well.

I have just added HTML element selector with the body. It has done the job.
$("html,body").on({
    'mousedown': $.proxy(this.clickOutSide, this),
    'touchstart': $.proxy(this.clickOutSide, this)
});

**Comment by mjolnic** [comment]
@aamirshahzad _'body click is not triggered on button and anchors with return statement'_

please provide more info with a complete example to reproduce this issue. use JSFiddle.net or similar.
Thanks
