### ISSUE TITLE
[BUG]colorpicker use the wrong string parser when input one of some valid values

### ISSUE THREAD

**Issue by ppoo24** [mjolnic/bootstrap-colorpicker#104]
consider inputing an valid value: `rgba(37,37,115,0.41)`, then it will turn to `rgba(17,17,85,1)`.
then i ran into the code, found that it matched the wrong parser(line 425 at bootstrap-colorpicker.js): 
```js
/#?([a-fA-F0-9])([a-fA-F0-9])([a-fA-F0-9])/
```
 , and the match result object is:
```js
["115", "1", "1", "5", index: 11, input: "rgba(37,37,115,0.41)"]
```
yes, you will see it matched string `115`
the correct one should be `/rgba\(\s*(\d{1,3})\s*,\s*(\d{1,3})\s*,\s*(\d{1,3})\s*(?:,\s*(\d+(?:\.\d+)?)\s*)?\)/` absolutely.
maybe add some more limition to regular expression like `^` `$` is a way to solve this problem.

**Comment by mjolnic** [comment]
@ppoo24 thanks, definitely we need to fix this

**Comment by will-moore** [comment]
Strangely enough I have just tracked down this same bug.
I don't have much regex ability, but what seems to work for me is to move the offending parser to the end of the stringParsers list, so that it doesn't prematurely match.
