### ISSUE TITLE
ColorPicker out of screen

### ISSUE THREAD

**Issue by vicentor** [mjolnic/bootstrap-colorpicker#107]
I can't seem to be able to keep it inside the screen like dropdown-menu-right would do.

See attached file
![probz](https://cloud.githubusercontent.com/assets/2099885/6335902/b964e520-bb6c-11e4-868f-222cf35601bc.png)

**Comment by neogetz** [comment]
Same problem here. Sometimes I have to zoom out the sceen to 90% to be able to select the appropriate color.

**Comment by mjolnic** [comment]
hello in version 2.1 you have the new align option that solves this (though is not automatic yet) #65

**Comment by vicentor** [comment]
Adding this in the options did the trick:
align: 'right'

Thank you!
