### ISSUE TITLE
Wrong input value when using color name

### ISSUE THREAD

**Issue by sqal** [mjolnic/bootstrap-colorpicker#110]
Go to the demo fiddle: http://jsfiddle.net/4ery3Lpr/ and paste into an input some color e.g. "red". Picker returns black color everytime. Shouldn't plugin recognize that entered value is an alias for a color and get a hex value for this color from colors object and then return proper color?

**Comment by mjolnic** [comment]
hi this is fixed in the release 2.1.1
It may take some time to take effect on cdnjs

**Comment by mjolnic** [comment]
@sqal http://jsfiddle.net/4ery3Lpr/1/

**Comment by sqal** [comment]
@mjolnic Awesome. Thank you :+1:
