### ISSUE TITLE
How to make it work on dialogs?

### ISSUE THREAD

**Issue by neotropic2023** [mjolnic/bootstrap-colorpicker#113]
I seen the examples and they work. I made my form, everything was working. The moment I plug it into my app and place in a bootstrap dialog, it never fires. No errors saying colorpicker is not a function. I tried so many methods, returns and checks if the colorpicker script is being loaded as well if the fields are found and it is and they all are there. I view firebug, click input nothing there either. I am so lost as why this is not firing. I have it with a series of other scripts, disabled them, still nothing. All files are present and there as well. In fact no errors at all what so ever. 

Worked in basic demo page, no dialog:
$("#background-color,#font-color,#link-color,#link-hover").colorpicker();
Not when implemented into my app.

At one point I was loading the HTML into a dialog afterwards, loaded when requested, then trying to fire colorpicker. I thought since it was not loading, it needed them to be loaded immediately from the DOM like some scripts. Nope, from my tests. Just nothing at all, grr.

If you have any interest checking it out and seeing for yourself, email me. The area is private and not making it public as it is in with a basic website editor within a user control panel on a live site (for animal breeders). I can give you my login. 

Thanks in advance. I may not reply until after the weekend as well.

**Comment by mjolnic** [comment]
Hi @neotropic2023 please, provide an example to reproduce the issue using https://jsfiddle.net/ or similar, otherwise I cannot help you.
Thanks.
