### ISSUE TITLE
Suggestion: add how to install on Readme.md

### ISSUE THREAD

**Issue by jamesjenner** [mjolnic/bootstrap-colorpicker#114]
Hi,

Just a thought, maybe you could add some markdown on how to install. I notice that the project is available via bower but wasn't obvious. The usual quickstart section may be helpful for some. For example:

    ##Quick Start

    - Clone the repository: `git clone http://github.com/mjolnic/bootstrap-colorpicker.git`
    - Install client dependencies via [Bower](http://bower.io): `bower install mjolnic-bootstrap-colorpicker`

**Comment by mjolnic** [comment]
thanks, I updated it
