### ISSUE TITLE
.colorpicker() is not a function

### ISSUE THREAD

**Issue by virgiliu** [mjolnic/bootstrap-colorpicker#115]
Running 

    jQuery('.has-colorpicker').colorpicker(); 

throws this error:

    jQuery(...).colorpicker is not a function

Colorpicker is included in the page and the above code is ran after the document finishes loading.
jQuery version is 2.1.1.

**Comment by SiteSplat** [comment]
You'll need to set up a test on jsfiddle and show the above.

**Comment by virgiliu** [comment]
http://jsfiddle.net/22bL4jq1/

**Comment by mjolnic** [comment]
@virgiliu you are using a raw github file for the plugin js. Raw github source files are always served as text/plain, there is the problem.

**Comment by virgiliu** [comment]
I used that only for the fiddle as I don't have a public server from which to serve the select2 file.
