### ISSUE TITLE
Setting options not working

### ISSUE THREAD

**Issue by thekaladar** [mjolnic/bootstrap-colorpicker#116]
Seems like setting attributes via option or when initializing doesn't work.

See JSfiddle:
http://jsfiddle.net/7jyf6331/6/

For example:
$('#bobo').colorpicker('color', '#ff0000');
Results in:
TypeError: inst[option].apply is not a function

**Comment by MarcGodard** [comment]
Also not working for align.

**Comment by mjolnic** [comment]
@thekaladar @MarcGodard all valid options are specified in the documentation and they can only be colorpicker API methods.
If you want to access the colorpicker data directly you should use __.data('colorpicker')__

**Comment by oromanos** [comment]
Specifying the color while instantiating does not work too
