### ISSUE TITLE
Colorpicker Positioning

### ISSUE THREAD

**Issue by Untit1ed** [mjolnic/bootstrap-colorpicker#118]
Is there a way to position the color-picker pop-up? 
It worked fine previously when in `2.0` when my `.input-group-addon` is placed before my `.form-control` input element, not after like in your examples.

What I see now: https://jsfiddle.net/DTcHh/8258/ (`2.1` the pop-up is outside the form)
What it was before: https://jsfiddle.net/DTcHh/8259/ (`2.0` the pop-up is inside the form. **Preferred solution**)

**Comment by ASeeto** [comment]
It looks like there's an option provided to adjust the alignment of the color picker :)

Try adjusting your fiddle to the following:
```
 $(function () {
     $('.cp').colorpicker({align:'left'});
 });
```

**Comment by Untit1ed** [comment]
@ASeeto, great, thanks
