### ISSUE TITLE
Preset "swatches" of colours

### ISSUE THREAD

**Issue by robertlagrant** [mjolnic/bootstrap-colorpicker#119]
Rather than give users the ability to pick any colour, is it possible to limit them to only having certain colours from a predefined swatch?

**Comment by mjolnic** [comment]
@robertlagrant not for now, it is planned for v3.0, but I am not really sure when it will be finished and deployed to master, depends on my time and the community help. Of course all the help will be welcome for speeding up the release =)

![bscp3](https://cloud.githubusercontent.com/assets/122741/3277779/608f4616-f38f-11e3-9596-42226b4ace70.png)

**Comment by robertlagrant** [comment]
Aaah okay thanks :)

**Comment by itsjavi** [comment]
You can also hide the selectors via CSS or remove them completely from the template
http://jsfiddle.net/0vopxm13/158/
