### ISSUE TITLE
Error when color selection starts from white

### ISSUE THREAD

**Issue by lukaszwado** [mjolnic/bootstrap-colorpicker#121]
When your input value is equal to #ffffff and you open color mixer to select the color, somehow after click, it always change color to shade of red instead of grey as expected.

**Comment by lukaszwado** [comment]
Can I expect that you will fix the issue? Or should I try to fix it on my own?

**Comment by SiteSplat** [comment]
Posting a fiddle would help the author to narrow down the issue and make sure its not an error on your side instead. 

If you already know this is somewhat a "bug" and would like to attempt a fix you can post it here for review and testing so that everybody can chip in.
