### ISSUE TITLE
No preview color until close

### ISSUE THREAD

**Issue by markusjohnsson** [mjolnic/bootstrap-colorpicker#122]
For some reason I don't get a preview color until after I close the color picker. JS Fiddle (just click the grey area in the input group to open color picker and then click it again to close): http://jsfiddle.net/smoLujex/

I think colorpicker misses that the value of the input has changed .. and it doesn't respect setValue.. But when the color picker is closed, it reads the value from the input..

**Comment by mjolnic** [comment]
Hi @markusjohnsson , I found the problem, the setValue should call update with force=true https://github.com/mjolnic/bootstrap-colorpicker/blob/master/src/js/colorpicker.js#L307

I will work on a fix, but at the moment you could trigger 'updateComponent' manually

     ($(element))
        .colorpicker('setValue', ko.unwrap(valueAccessor())).colorpicker('updateComponent');

Thanks

**Comment by markusjohnsson** [comment]
The workaround works like a charm!

Thank you for the tip and thanks for this useful project :)
