### ISSUE TITLE
Can't preset color

### ISSUE THREAD

**Issue by RobertLarsen** [mjolnic/bootstrap-colorpicker#123]
When setting the color of the colorpicker, it seems to be set internally but not shown in the graphics.
I have tried:

```
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="css/bootstrap-colorpicker.css" type="text/css" media="screen" title="no title" charset="utf-8">
    <script src="js/jquery-2.1.4.js" type="text/javascript" charset="utf-8"></script>
    <script src="js/bootstrap-colorpicker.js" type="text/javascript" charset="utf-8"></script>
    <script>
        $(function() {
            $('#color1').colorpicker({
                inline : true,
                container : true,
                color : '#ff00ff'
            });
            $('#color2').colorpicker({
                inline : true,
                container : true
            });
            $('#color2').colorpicker('setValue', '#ff00ff');
            $('#color2').colorpicker('update');
        });
    </script>
</head>
<body>
    <div id='color1'/>
    <div id='color2'/>
</body>
</html>
```

But the color is not shown. If I change the alpha value in the picker, it is updated and the right color is shown.

**Comment by tagrudev** [comment]
I am having the same issue

**Comment by alisatee** [comment]
Same. Actually, none of the option parameters seem to work.

**Comment by rio2311** [comment]
Same issue, any solutions?

**Comment by rio2311** [comment]
RobertLarsen, it looks like you don't have a place to store color value by default, like in example with [input] element. In your case try to add property to your div: data-color="rgb(255, 255, 255)". Setting both values through input and js constructor worked for me

```
<div class="input-group colorpicker">
   <input  type="text" value="#00FF00" class="form-control" />
   <span  class="input-group-addon"><i></i></span>
</div>
```

```
$('.colorpicker').colorpicker({ color:"#00FF00", format:'hex'});
```

**Comment by mjolnic** [comment]
@RobertLarsen Hi, could you reproduce this in jsFiddle, like specified in the CONTRIBUTING.md guidelines. You will find the template there. Thanks

**Comment by hitchcott** [comment]
Also had this issue with `2.2.0`, surprisingly. Also, `setValue` didn't work.

Workaround for now is to manually invoke `coloricker('update', true)`.

**Comment by mjolnic** [comment]
fixed in the last commits
