### ISSUE TITLE
Create an AngularJS directive version

### ISSUE THREAD

**Issue by aendrew** [mjolnic/bootstrap-colorpicker#124]
Hi!
I used to use Bootstrap's JavaScript in my AngularJS project, but have gradually been migrating entirely to [Angular Bootstrap](https://angular-ui.github.io/bootstrap/)'s directives. Alas, this screws stuff up because bootstrap-colorpicker relies on Bootstrap's dropdown.

To that end — mind if I fork this and build it as a pure AngularJS directive?

**Comment by mjolnic** [comment]
Hi @aendrew no problem, you are totally free to fork it, but if it ends up being a totally separated project I would suggest you to change the name.

**Comment by newmanw** [comment]
@aendrew did you fork and create an angular directive?
