### ISSUE TITLE
Uncaught ReferenceError: $ is not defined

### ISSUE THREAD

**Issue by techpulse** [mjolnic/bootstrap-colorpicker#125]
Not sure why, copied/pasted your code and included javascript above it.

**Comment by mjolnic** [comment]
Hi @techpulse that's not a valid issue, please read the guidelines and edit your report https://github.com/mjolnic/bootstrap-colorpicker/blob/master/CONTRIBUTING.md
Thanks for understanding

**Comment by mjolnic** [comment]
@techpulse any updates about this or should I close this issue?

**Comment by techpulse** [comment]
Yes

**Comment by techpulse** [comment]
<link href="assets/colorpicker/css/bootstrap-colorpicker.css" rel="stylesheet">

<div class="input-group demo2">
    <input type="text" value="" class="form-control" />
    <span class="input-group-addon"><i></i></span>
</div>
<script>
    $(function(){
        $('.demo2').colorpicker();
    });
</script>
     <script src="//code.jquery.com/jquery-2.1.4.min.js"></script>
<script src="assets/colorpicker/js/bootstrap-colorpicker.js"></script>
<script src="assets/colorpicker/js/bootstrap-colorpicker.min.js"></script>

this is what i have, dont work

**Comment by techpulse** [comment]
![mpcww9a](https://cloud.githubusercontent.com/assets/12190261/8701516/7b9d9672-2b12-11e5-8840-1defc40c3f29.png)

**Comment by techpulse** [comment]
function that are on that line is
<script>
    $(function(){
        $('.demo2').colorpicker();
    });
</script>

**Comment by techpulse** [comment]
$(function(){
        $('.demo2').colorpicker();
    });

**Comment by techpulse** [comment]
![9e5fcvj](https://cloud.githubusercontent.com/assets/12190261/8701585/0b9f51de-2b13-11e5-8192-ac6b18ceb292.png)

looks like that lol

**Comment by mjolnic** [comment]
Please, reproduce the problem in jsfiddle following the contributing guidelines.

In your pastebin you are not including the bootstrap library. Please read and follow the contributing guidelines (that I posted in my first comment) before reporting issues. Thanks
