### ISSUE TITLE
Use a variable for resources path

### ISSUE THREAD

**Issue by ClementParis016** [mjolnic/bootstrap-colorpicker#130]
Would it be possible that you use an "overridable" variable in the less source code in order to define resources path (actually, the path to images files)?

I'm trying to import the less source file in my app from the node_modules folder, but the path to images turns to be wrong when importing the less file from another location.

As an example, Twitter Bootstrap as an `@icon-font-path` variable which you can set yourself to solve the same issue :)

Or if you have any other/better idea to make usage of this cool colorpicker with npm easier, please do.

**Comment by MartijnDwars** [comment]
+1, I'm having the same issue.

**Comment by mjolnic** [comment]
@ClementParis016 having a separated variable in the less file will work?

    @imgPath: "../img/bootstrap-colorpicker/";
    
    .bgImg(@imgFilename){
        background-image: url("@{imgPath}@{imgFilename}");
    }

**Comment by ClementParis016** [comment]
Yes @mjolnic, this is the idea.

Then you can use it like this to override it on purpose: 

```less
@import "../node_modules/bootstrap-colorpicker/src/less/colorpicker"; // import first
@imgPath: "../img/smthg/"; // override after
```

Also, it would be a good idea to document it since people could be using the same variable name without knowing it which could lead to conflicts (or at least confusion) ;)

**Comment by mjolnic** [comment]
Thanks @ClementParis016 it has been changed since version 2.3
