### ISSUE TITLE
Weird UI behavior of color palette when color set to #FF0000

### ISSUE THREAD

**Issue by ghost** [mjolnic/bootstrap-colorpicker#134]
When setting default color to red (#FF0000), and start picking red tone from palette, color changes very unexpectedly, please check jsfiddle below

http://jsfiddle.net/sb665dph/1/

**Comment by mjolnic** [comment]
hi @rio2311 I can't reproduce the issue. Can you be more specific? Which OS and Browser are you using?

**Comment by rio2311** [comment]
Sorry for incomplete description, @mjolnic .

Browser/OS - Ubuntu12.04+Firefox(Latest), MacOSX + Safari(Latest).

In jsfiddle above try to drag picker from upper right to bottom left.

I expect, that only picked color should be changed, but instead, whole color palette changes from red to black. 

If you will change initial color value from #FF0000 to #FF0001, the issue will not appear. Looks like something wrong with value parser?

**Comment by mjolnic** [comment]
@rio2311 oh I see now the problem, definitely something might be wrong with the pure red palette

**Comment by nerdybynature** [comment]
This also happens when there is no initial value. Check the "enable/disable" example on https://mjolnic.com/bootstrap-colorpicker/

**Comment by mjolnic** [comment]
This has been fixed
