### ISSUE TITLE
defining colorSelectors via data-* attribute coming from server JSONObject

### ISSUE THREAD

**Issue by sebastianriemer** [mjolnic/bootstrap-colorpicker#135]
I have a problem when trying to populate predefined color selectors via the attribute *data-color-selectors*.

I am creating a JSONObject on the server-side like this: 

```java
JSONObject defaultColors = new JSONObject();
defaultColors.put("default-1", "#11aa33");
defaultColors.put("default-2", "#159159");
defaultColors.put("default-3", "#636363");
model.addAttribute("defaultColors", defaultColors);
```

```jsp
Then on my JSP-page I render my control like this:
    <div class="input-group"
    data-format="rgb"
    data-color-selectors='${defaultColors}'>
```
Finally, I initialize the control calling: 
```javascript
    $inputGroup.colorpicker({});
```

As result I get three buttons below the control representing the three pre-defined colors I supplied. However they are in **random order**, which Is as I learned **a result of JSONObject properties being unordered by definition**.

Please refer to these links:
http://stackoverflow.com/questions/4515676/keep-the-order-of-the-json-keys-during-json-conversion-to-csv
http://stackoverflow.com/questions/24884381/keep-listlinkedhashmapstring-object-order-when-converstion-to-jsonarray
http://stackoverflow.com/questions/32088666/order-of-json-format-is-getting-changed

Please note, that when I am initializing the colorSelectors via javascript, the ordering is as defined in the javascript object.

I've managed to fix this issue by changing the code, mainly by:
- changing the structure of the colors object, giving it two properties: **name** and **color**
- adapting the *toAlias* function like this (approx. line 333):
```javascript
toAlias: function(r, g, b, a) {
        var rgb = this.toHex(r, g, b, a);
        for (var alias in this.colors) {
          if (this.colors[alias].color === rgb) {
            return this.colors[alias].name;
          }
        }
        return false;
      }
```
- change the initialization part of the colorSelectors like this (approx. line 648):
```javascript
if (this.options.colorSelectors) {
        var colorpicker = this;
        $.each(this.options.colorSelectors, function(name, item) {
          var $btn = $('<i />').css('background-color', item.color).data('class', item.name);
          $btn.click(function() {
            colorpicker.setValue($(this).css('background-color'));
          });
          colorpicker.picker.find('.colorpicker-selectors').append($btn);
        });
        this.picker.find('.colorpicker-selectors').show();
      }
```
- as well as checking the returned value from the toAlias-call in *updateInput* (approx. line 782)
```javascript
var alias = color.toAlias();
            if (alias) {
              val = alias;
            }
```
- and of course, I now populate a JSONArray on the server-side like this:
```java
JSONArray defaultColors = new JSONArray();
			JSONObject def1 = new JSONObject();
			def1.put("name", "default-1");
			def1.put("color", "#ffaa33");
			defaultColors.put(def1);
```

Et voilà! The ordering is the same as the insert order and thus can be controlled.

Am I missing something important here? If so, please give me a shout.

Otherwise, thank you for this colorpicker - i like it!

**Comment by mjolnic** [comment]
Hi @sebastianriemer it seems a server-side corner case that makes the plugin work like that. Please feel free to fork the library, apply your changes and perform a pull request, so we will be able to see the code differences, test them and find the proper solution.

Thanks
