### ISSUE TITLE
Nugget installation

### ISSUE THREAD

**Issue by LanzFR** [mjolnic/bootstrap-colorpicker#142]
Hi Javier,

First thanks for this great work !
Do you plan to provide an installation via Nugget ? There is one (https://www.nuget.org/packages/bootstrap-colorpicker/) but with a dependency on bootstrap ≥ 3.3.5  unlike your plugin which works with BS v2.

Thanks in advance for your answer
Lanz

**Comment by mjolnic** [comment]
Hi @LanzFR I think that it's easier to ask the package owner in Nuget to decrease the required BS version. Sorry but I don't want to create an account there cause I don't use .NET and it will be another thing to maintain for this project (that is already available in multiple different ways).

Thanks

**Comment by sadjadbp** [comment]
@mjolnic @LanzFR I've created https://www.nuget.org/packages/bootstrap-colorpicker/ package on NuGet. Let's first thanks @mjolnic for his great work on this component, I'm ok to change the dependency, @mjolnic do you have exact BS version that your CP code depends on? so I can change the package

**Comment by LanzFR** [comment]
Thanks for your answer @mjolnic, I understand your perspective.

Hi @sadjadbp,
Actually I use BS 2.3.2, but it should be better to align Nugget's dependencies on those defined by @mjolnic, ie bootstrap ≥ 2.
Thanks
Lanz

**Comment by sadjadbp** [comment]
@LanzFR can you provide specific version that this component works with? BS v2.X?

**Comment by LanzFR** [comment]
@sadjadbp as far I understand it should work with BS v2.0.0

**Comment by sadjadbp** [comment]
@LanzFR thanks and thanks again for this great addon
@mjolnic done, updated to BS 2.3.1, the earliest one I've found on NuGet

**Comment by LanzFR** [comment]
@sadjadbp many thanks this is perfect !

**Comment by mjolnic** [comment]
Thanks @sadjadbp
