### ISSUE TITLE
Not showing when ajax loaded

### ISSUE THREAD

**Issue by stygiansabyss** [mjolnic/bootstrap-colorpicker#15]
If the page with the colorpicker is loaded through ajax, the color picker is not displayed at all.  Is there any way around this?

Thanks :)

**Comment by darmie** [comment]
Please how did you fix this?

**Comment by mjolnic** [comment]
You have to execute your javascript once you loaded your ajax content and is available in the DOM. Google is your friend :)
 http://stackoverflow.com/questions/22226628/initialize-the-jquery-plugin-after-ajax-content-loads

**Comment by darmie** [comment]
Thanks, already solved it. I forgot to close this thread.

**Comment by kjjdion** [comment]
$(document).ajaxComplete(function () {
        $('.my-colorpicker').colorpicker();
    });
