### ISSUE TITLE
Android Chrome: When trying to drag on color picker input gets focus and keyboard pulls up preventing dragging.

### ISSUE THREAD

**Issue by shekky** [mjolnic/bootstrap-colorpicker#150]
Using on android with chrome, when I try to touch and drag on the color picker, the input gets focus and the soft keyboard pulls up and I cannot drag on the color picker.

Chrome v 47.0.2526.83

**Comment by mjolnic** [comment]
That's a default Android chrome behavior and we cannot do very much about it. 
I wouldn't like to force the focus into the colorpicker or other hacky stuff.
Use the plugin as a component or inline instead, for mobile.
