### ISSUE TITLE
Zoom on Android Chrome breaks color picker

### ISSUE THREAD

**Issue by shekky** [mjolnic/bootstrap-colorpicker#151]
When zooming in on the page, the color picker doesn't work correctly.The selector stays at the top left no matter where I click on the color picker.

**Comment by maruel** [comment]
Related, using CSS Style "transform: scale(2)" or "zoom: 2" leads to the same problem. I wanted to make it bigger for use on a tablet but sadly it's unusable with any translation.

**Comment by mjolnic** [comment]
Hi, there is a demo in the docs for making the widget bigger.
https://mjolnic.com/bootstrap-colorpicker/

**Comment by shekky** [comment]
The issue happens when I zoom the screen in manually with my fingers on the Android screen. The widget's cursor doesn't recognize this and it doesn't position itself correctly. It stays in the upper left corner.

**Comment by maruel** [comment]
Thanks @mjolnic, I did use the code in the demo, but the widget's behavior still incorrect as stated by @shekky.

**Comment by mjolnic** [comment]
yes, unfortunately it needs more debugging in mobile browsers. I would also like to introduce a bigger selector for the finger. In general mobile support needs improvements, now that the most of the websites are mobile-first.

btw, I was not able to reproduce this on my android 6 chrome, could you provide a fiddle with the code that causes the error?thanks

**Comment by shekky** [comment]
I can reproduce this behaviour with any of the color pickers on the demo page.

**Comment by shekky** [comment]
I'm using Chrome v49.0.2623.105. Should the Android version make any difference?

**Comment by shekky** [comment]
Anyways... I'm using android v4.3

**Comment by mjolnic** [comment]
Ok, so is it a bug in the docs page only? @shekky @maruel 

because I tested it on a separated fiddle and it works fine http://fiddle.jshell.net/qt8x13y8/show/light/

**Comment by shekky** [comment]
Yes, the fiddle works perfectly.

**Comment by mjolnic** [comment]
The problem comes on focus and automatic zoom of mobile devices, but a `viewport` meta header solves the problem:
http://fiddle.jshell.net/qt8x13y8/4/
http://fiddle.jshell.net/qt8x13y8/4/show/

**Comment by shekky** [comment]
Yeah, the first link works. The second one though, I think the meta tag is getting removed and it has the bug. But it look like the having the meta tag solves the issue. Thanks.
