### ISSUE TITLE
No transparency sliders

### ISSUE THREAD

**Issue by dadixon** [mjolnic/bootstrap-colorpicker#152]
Is there a way to take the transparency sliders out and not support it at all?

**Comment by nmjbhoffmann** [comment]
There is, basically only allow hex inputs, so
$('.class').colorpicker({
    format:'hex'
})

**Comment by dadixon** [comment]
That worked. Thanks

**Comment by mjolnic** [comment]
You can also customize the widget template and remove the alpha bar:

https://github.com/mjolnic/bootstrap-colorpicker/blob/master/src/js/colorpicker-defaults.js#L55
