### ISSUE TITLE
Is there any method for disabling alpha value ?

### ISSUE THREAD

**Issue by EduardJS** [mjolnic/bootstrap-colorpicker#154]
Hello, wondering if there's any option as in the docs I can't see anything regarding that in order to disable the alpha value selector.

**Comment by mjolnic** [comment]
Please read #152

**Comment by mjolnic** [comment]
You can also customize the widget template and remove the alpha bar:

https://github.com/mjolnic/bootstrap-colorpicker/blob/master/src/js/colorpicker-defaults.js#L55
