### ISSUE TITLE
I'm getting an error when trying to install it with npm

### ISSUE THREAD

**Issue by francdore** [mjolnic/bootstrap-colorpicker#159]
Hi, I'm getting in error with npm install bootstrap-colorpicker.

npm WARN install Couldn't install optional dependency: Unsupported

> bufferutil@1.1.0 install C:\xampp\htdocs\everlab\node_modules\bufferutil
> node-gyp rebuild

![image](https://cloud.githubusercontent.com/assets/2630949/14641060/bd08ed6a-0644-11e6-8eeb-151cca2452bc.png)

**Comment by mjolnic** [comment]
it seems you have issues with your current node/npm installation, it's not an issue of the plugin itself.
