### ISSUE TITLE
Changing input now fires change() event

### ISSUE THREAD

**Issue by dozer47528** [mjolnic/bootstrap-colorpicker#160]
It was fixed in 2013. https://github.com/mjolnic/bootstrap-colorpicker/pull/18

But doesn't work in the newest version.

**Comment by mjolnic** [comment]
The only events that are fired are the ones specified in the documentation https://mjolnic.com/bootstrap-colorpicker/
`changeColor` event was adopted in order to avoid problems with the native `change` event.

**Comment by dozer47528** [comment]
Thanks, I will try it.
