### ISSUE TITLE
Accessing a colorpicker after the DOM has loaded

### ISSUE THREAD

**Issue by bestdamnfriend** [mjolnic/bootstrap-colorpicker#166]
If I create a colorpicker element after the DOM has loaded, it does not seem to work. I would normally go and change all `.click()` events to `.on("click", function() {})`, but I see that the JS file already has this format. Is there any way I can add a colorpicker element to the page once the page has loaded?

**Comment by mjolnic** [comment]
Hi, this sounds very weird, have you take a look to the documentation and the samples?

Please, also take a look to the guidelines for contributing and publishing issues: https://github.com/mjolnic/bootstrap-colorpicker/blob/master/CONTRIBUTING.md

Then provide a non working example, reproducing your issue on a JSFiddle or similar.

Thanks
