### ISSUE TITLE
Compatibility with Interactjs on tablets?

### ISSUE THREAD

**Issue by cabo1956** [mjolnic/bootstrap-colorpicker#173]
Dont know if the issue is on interactjs's side or not, but it doesnt seem to work with it on tablets. If i put the colorpicker inside an interactjs element it wont appear when clicked on. Not sure what is causing it and i cant see any errors in the console. Anyone have any idea?

**Comment by mjolnic** [comment]
If the element is generated by javascript you must initialize the colorpicker plugin after creating the element.
