### ISSUE TITLE
Example codes are not working

### ISSUE THREAD

**Issue by jcfrog** [mjolnic/bootstrap-colorpicker#174]
Hi,
on this page http://zzzhan.github.io/bootstrap-colorpicker-plus/ the example codes are not working. I mean the source in `<pre>` sections is different from the real code.
For instance in EXAMPLE you have
`demo2.on('changeColor', function(e){ 
  if(e.color==null) { ...
`
In real code it's:
`demo2.on('changeColor', function(e,color){ 
   if(color==null) { ...`
(which works fine)

Thanks for the colorpicker!

**Comment by mjolnic** [comment]
Hi, I can see them working in different browsers.
