### ISSUE TITLE
Add align option

### ISSUE THREAD

**Issue by greypants** [mjolnic/bootstrap-colorpicker#65]
![image](https://f.cloud.github.com/assets/647549/2456205/6c9945c2-af12-11e3-99df-a96ac5440fd8.png)

It'd be nice to change the default alignment so that the color picker doesn't go offscreen if the element is aligned to the right edge of the browser (pictured above).

**Comment by mjolnic** [comment]
Hi @greypants how is your progress for this? Should I close this issue? thanks

**Comment by greypants** [comment]
Forgot again! I'll do it now - my day's wide open.

**Comment by sqal** [comment]
:+1: for this. I have a similar issue, but my colorpicker is cut off when he goes out of bottom edge of the screen - http://prntscr.com/66rrkq. This is happening, because body is overflow: hidden. So, It'd be great if colorpicker was correctly positioned top/bottom as well :)

**Comment by mjolnic** [comment]
:+1: thanks @greypants !

**Comment by greypants** [comment]
![you got it dude](https://media.giphy.com/media/HjPbLbmep2aJO/giphy.gif)
