### ISSUE TITLE
Support for "transparent"

### ISSUE THREAD

**Issue by SirRawlins** [mjolnic/bootstrap-colorpicker#92]
Hello Guys,

I'm looking for support of transparent as a colour within the picker. At the moment when setting this it seems to reset the field to #000000 which isn't what I'm after.

I couldn't see anything for this already filed in the issues list - is this something which is planned? Or has been rejected in the past for some reason?

Thanks,

Robert

**Comment by leonardteo** [comment]
Any status on this? This would be great.

**Comment by nukepoof** [comment]
As a quick fix I was able to get it working with this

```javascript
updateComponent: function(val) {
	if(this.input.val() == ''){
		val = 'transparent'
	} else {
        val = val || this.color.toString(this.format);
        if (this.component !== false) {
            var icn = this.component.find('i').eq(0);
            if (icn.length > 0) {
                icn.css({
                    'backgroundColor': val
                });
            } else {
                this.component.css({
                    'backgroundColor': val
                });
            }
        }
    }
    return val;
},
```
